### PR TITLE
Update Binary.hs

### PR DESCRIPTION
**Pull request by wojtnar**
Add support for old BSON binary (2) subtype for binary data, which old UUID (3) already had.

### CODE REVIEW

**Comment by gregwebs** [comment]
Looks good to me. I will let @VictorDenisov look at this and release it.

**Comment by VictorDenisov** [comment]
Looks good to me as well. I'll add a change log file and release it. Do we want to migrate mongodb library to the new version of bson?

**Comment by gregwebs** [comment]
@VictorDenisov not sure what exactly you are referencing. I think @knsd was working on a better bson implementation. Personally i would say that I am just glad there is finally not a huge performance penalty in the driver anymore :)

**Comment by wojtnar** [comment]
Please migrate mongoDB, too. I had this issue (unhandled subtype 2) reading a database created years ago, but running on mongoDB 2.8.

**Comment by VictorDenisov** [comment]
@gregwebs it turned out I don't have right to upload bson packages - only mongodb packages.

**Comment by gregwebs** [comment]
@VictorDenisov you should have access now. Sorry I was confused about what you were saying :)
This is a breaking change for pattern matching. The ideal would be to use cabal version macros so that mongoDB can be compatible with both. But if you don't want to do that I would say do a version bump of mongoDB to leave yourself room in the unlikely case you want to backport a change to the older mongoDB that is not compatible with the newer bson.

**Comment by VictorDenisov** [comment]
Pardon me. I think I confused everyone including myself. This change allows us to read a wider range of binary representations. It doesn't add any new subtypes to bson.  It means we can bump only minor version. Currently mongodb doesn't pay attention to what minor version is. It means I can bump minor version of bson and no action on mongodb side is required. Am I correct?

**Comment by wojtnar** [comment]
Yes, correct.

**Pull request merged**
